### ISSUE TITLE
不能登陸

### ISSUE THREAD

**Issue by yuan-shen** [didi12121/AutoCheckIn#1]
在運行後跳出的畫面會一直重新整理

**Comment by didi12121** [comment]
微博的反爬虫机制更新了，我换了一种方法，目前还在测试，已经稳定十天了

**Comment by didi12121** [comment]
> 在運行後跳出的畫面會一直重新整理
看看这个新的用python写的[auto__checkin__py](https://github.com/didi12121/auto__checkin__py)
